export default {
  login: 'paulodantasrj',
  id: 42381779,
  node_id: 'MDQ6VXNlcjQyMzgxNzc5',
  avatar_url: 'https://avatars.githubusercontent.com/u/42381779?v=4',
  gravatar_id: '',
  url: 'https://api.github.com/users/paulodantasrj',
  html_url: 'https://github.com/paulodantasrj',
  followers_url: 'https://api.github.com/users/paulodantasrj/followers',
  following_url:
    'https://api.github.com/users/paulodantasrj/following{/other_user}',
  gists_url: 'https://api.github.com/users/paulodantasrj/gists{/gist_id}',
  starred_url:
    'https://api.github.com/users/paulodantasrj/starred{/owner}{/repo}',
  subscriptions_url: 'https://api.github.com/users/paulodantasrj/subscriptions',
  organizations_url: 'https://api.github.com/users/paulodantasrj/orgs',
  repos_url: 'https://api.github.com/users/paulodantasrj/repos',
  events_url: 'https://api.github.com/users/paulodantasrj/events{/privacy}',
  received_events_url:
    'https://api.github.com/users/paulodantasrj/received_events',
  type: 'User',
  site_admin: false,
  name: 'Paulo Dantas',
  company: null,
  blog: 'https://www.linkedin.com/in/paulodantas',
  location: 'Rio de Janeiro, Brasil',
  email: null,
  hireable: null,
  bio: 'Software Development Engineer, Mobile Apps (Android)',
  twitter_username: null,
  public_repos: 17,
  public_gists: 0,
  followers: 3,
  following: 2,
  created_at: '2018-08-14T14:13:50Z',
  updated_at: '2021-02-09T19:29:22Z',
}
